# -*- coding: utf-8 -*-
{
    "name": "Sportobello Sport Club",
    "summary": "Sport club and coaches management",
    "description": "Sport club management module for managing sport clubs and coaches",
    "author": "MG",
    "website": "https://www.sportobello.com",
    "category": "Tools",
    "sequence": 5,
    "version": "18.04.07",
    "depends": [
        "base",
        "kojto_landingpage",
        "kojto_contacts",
        "sportobello_kojto_inherit",
    ],
    "data": [
        "data/sportobello_groups.xml",
        "security/ir.model.access.csv",
        "views/sportobello_sportsclub_views.xml",
        "views/sportobello_coaches_views.xml",
        "views/sportobello_athletes_views.xml",
        "views/sportobello_athlete_anthropometric_tracker_views.xml",
        "views/sportobello_athlete_overtraining_tracker_views.xml",
        "views/sportobello_athlete_functional_test_tracker_views.xml",
        "views/sportobello_athlete_training_group_views.xml",
        "views/sportobello_control_races_views.xml",
        "views/sportobello_control_race_types_views.xml",
        "views/sportobello_competitions_views.xml",
        "views/sportobello_training_sessions_views.xml",
        "views/sportobello_training_session_elements_views.xml",
        "views/sportobello_training_session_lines_views.xml",
        "views/sportobello_menu_items.xml",
        "views/sportobello_buttons.xml",
    ],
    'installable': True,
    'application': False,
}
